name: dart_dev
description: A sample command-line application.
publish_to: 'none'
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  # dart后端框架
  shelf: ^1.4.1
  # dart后端框架  
  shelf_router: ^1.1.4
  # dart后端框架
  shelf_static: ^1.1.3
  shelf_multipart: ^2.0.0
  #后端自定义插件
  api_mana:
    path: ../api_mana

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
